version: '3.9'

services:
  postgres:
    image: postgres:16.3
    restart: always
    container_name: boardlifyPostgresDB
    environment:
      POSTGRES_DB: boardlifyPostgresDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: boardlifyMongoDB
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: boardlifyMongoDB
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: 1234
    volumes:
      - ./mongo:/data/db
