

version: '3.9'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: boardlifyDB
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: 1234
    volumes:
      - ./mongo:/data/db